Numpy (Numerical Python)

1. 넘파이 설치 확인

In [1]:
import numpy as np
print(np.__version__)

2.3.5


### 2. 넘파이 배열 (ndarray) 생성과 속성 확인

In [3]:
a1 = np.array([1, 2, 3])
print(a1, a1.dtype, a1.ndim, a1.shape, a1.size)
a2 = np.array((1, 2, 3))
print(a2, type(a2), a2.dtype, a2.ndim, a2.shape, a2.size)

[1 2 3] int64 1 (3,) 3
[1 2 3] <class 'numpy.ndarray'> int64 1 (3,) 3


In [5]:
a3 = np.array([[1, 2, 3], [4, 5, 6]])
print(a3)
print(type(a3), a3.dtype, a3.ndim, a3.shape, a3.size)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'> int64 2 (2, 3) 6


In [6]:
a1 = np.array([1, 2, 3], dtype=float)
print(a1, type(a1), a1.dtype, a1.ndim, a1.shape, a1.size)

[1. 2. 3.] <class 'numpy.ndarray'> float64 1 (3,) 3


In [7]:
a6 = np.array([1, 4, 5, '8'])
print(a6)
print(type(a6), a6.dtype, a6.ndim, a6.shape, a6.size)

['1' '4' '5' '8']
<class 'numpy.ndarray'> <U21 1 (4,) 4


In [8]:
a6 = np.array([1, 4, 5, '8'], int)
print(a6)
print(type(a6), a6.dtype, a6.ndim, a6.shape, a6.size)

[1 4 5 8]
<class 'numpy.ndarray'> int64 1 (4,) 4


In [9]:
test_list = [[1, 4, 5, 8], [1, 4, 5]]
np.array(test_list)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### 3. Indexing

In [10]:
d3 = np.arange(12).reshape(2, 2, 3)  # 0 ~ 11
print(d3)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [13]:
d3[0] = 50
print(d3)

[[[50 50 50]
  [50 50 50]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [14]:
d3[1,0] = 30
print(d3)

[[[50 50 50]
  [50 50 50]]

 [[30 30 30]
  [ 9 10 11]]]


### 4. slicing

In [20]:
d2 = np.arange(1,11).reshape(2,-1)
print(d2)
d2[:,:] = -1
print(d2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


### 5. Boolean Indexing

In [22]:
data = np.array([4, 6, 7, 3, 2, 0])
print(data > 3)
print(data[data > 3])


[ True  True  True False False False]
[4 6 7]


### 6. 넘파이 배열의 정렬

In [ ]:
# [연습문제] 성적순으로 출력 (내림차순)
names = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
scores = np.array([78, 95, 84, 98, 88])

scores_sorted_index = np.argsort(scores)[::-1]
print(scores_sorted_index)

# 팬싱인덱스적용
print(names[scores_sorted_index])

[3 1 4 2 0]
['Kate' 'Mike' 'Samuel' 'Sarah' 'John']
